project:
  type: website
  output-dir: docs

website:
  title: "rencyclopedia"
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Main"
      contents:
      - href: index.qmd
        text: Home
      - about.qmd
    - section: "G"
      contents:
        - geocoding.qmd
    - section: "Q"
      contents:
      - qrcodes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

